#!/usr/bin/env bash
set -euo pipefail

echo "=== PE Document Intelligence Platform — Bootstrap ==="
echo ""

# Check prerequisites
command -v docker >/dev/null 2>&1 || { echo "Error: docker is not installed."; exit 1; }
command -v docker compose >/dev/null 2>&1 || { echo "Error: docker compose is not available."; exit 1; }

# Create data directories
echo "[1/6] Creating data directories..."
mkdir -p data/upload data/parsed data/schemas

# Copy .env if not exists
if [ ! -f .env ]; then
  echo "[2/6] Creating .env from .env.example..."
  cp .env.example .env
  echo "  ⚠ Edit .env with your API keys before using the platform."
else
  echo "[2/6] .env already exists, skipping."
fi

# Copy backend .env if not exists
if [ ! -f backend/.env ]; then
  echo "  Creating backend/.env from .env..."
  cp .env backend/.env
fi

# Start Docker services
echo "[3/6] Starting PostgreSQL and Weaviate..."
docker compose up -d

# Wait for PostgreSQL
echo "[4/6] Waiting for PostgreSQL..."
for i in $(seq 1 30); do
  if docker compose exec -T postgres pg_isready -U doc_intel >/dev/null 2>&1; then
    echo "  PostgreSQL is ready."
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "  Error: PostgreSQL did not become ready in 30s."
    docker compose logs postgres --tail=20
    exit 1
  fi
  sleep 1
done

# Wait for Weaviate
echo "  Waiting for Weaviate..."
for i in $(seq 1 30); do
  if curl -sf http://localhost:8080/v1/.well-known/ready >/dev/null 2>&1; then
    echo "  Weaviate is ready."
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "  Error: Weaviate did not become ready in 30s."
    docker compose logs weaviate --tail=20
    exit 1
  fi
  sleep 1
done

# Backend setup
echo "[5/6] Setting up backend..."
cd backend
if command -v uv >/dev/null 2>&1; then
  uv sync
  echo "  Running database migrations..."
  uv run alembic upgrade head
else
  python3 -m venv .venv
  source .venv/bin/activate
  pip install -r requirements.txt
  echo "  Running database migrations..."
  alembic upgrade head
fi

# Make `backend.evals.*` importable from any cwd.
# `uv sync` does not install the backend project itself, and uv marks venv
# files with the macOS UF_HIDDEN flag, which Python 3.13+ now uses as a signal
# to skip .pth files. A sitecustomize.py in site-packages is still imported
# regardless of the hidden flag, so we use that as the durable mechanism.
REPO_ROOT_ABS="$(cd .. && pwd)"
BACKEND_ABS="$(pwd)"
for sp in .venv/lib/python*/site-packages; do
  if [ -d "$sp" ]; then
    cat > "$sp/sitecustomize.py" <<PY
"""Auto-generated by init.sh. Do not edit — rewritten on every bootstrap."""
import os, sys
_REPO_ROOT = "${REPO_ROOT_ABS}"
_BACKEND = "${BACKEND_ABS}"
for _path in (_REPO_ROOT, _BACKEND):
    if os.path.isdir(_path) and _path not in sys.path:
        sys.path.insert(0, _path)
PY
  fi
done

cd ..

# Frontend setup
echo "[6/6] Setting up frontend..."
cd frontend
npm ci
cd ..

echo ""
echo "=== Bootstrap complete ==="
echo ""
echo "Services running:"
echo "  PostgreSQL  → localhost:5432"
echo "  Weaviate    → localhost:8080"
echo ""
echo "To start the app:"
echo "  Backend:  cd backend && uv run uvicorn src.main:app --reload --port 8000"
echo "  Frontend: cd frontend && npm run dev"
echo ""
echo "  Backend API:  http://localhost:8000/api/v1/health"
echo "  Frontend UI:  http://localhost:5173"
